# Generated by Django 5.0.4 on 2024-05-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categories_creator'),
        ('posts', '0006_alter_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
        ),
    ]
